### ISSUE TITLE
右上角 layer 圖層點擊不到

### ISSUE THREAD

**Issue by wastu01** [becory/covid-19-test-kit-tw#2]

**Comment by wastu01** [comment]
只有選到 販售店家 checkbox

**Comment by wastu01** [comment]
另外常用藥局的剩餘數量色號跟地圖不一致(不影響功能)

感謝製作網站

**Comment by becory** [comment]
Hi, @wastu01

> 只有選到 販售店家 checkbox

- 圖層功能未來是在想說看可不可以接PCR地圖之類的

> 另外常用藥局的剩餘數量色號跟地圖不一致(不影響功能)

- 你是說左邊圖標跟常用藥局的背景顏色不一致嗎？一個深一個淺
當初考量如果同樣的顏色，想說怕太多太重的顏色在右邊或是手機版下面很搶，導致使用者不易讀

<img width="715" alt="image" src="https://user-images.githubusercontent.com/13202145/167254605-9f205a56-b236-47bc-b081-ef35cd9a47c5.png">

您有比較好的建議嗎？或許相同顏色白色字？
<img width="756" alt="image" src="https://user-images.githubusercontent.com/13202145/167254946-485b6f59-9c01-437e-9736-7da8b40dfc1e.png">

**Comment by wastu01** [comment]
了解！白字也是個不錯的方式 
謝謝製作網站

**Comment by becory** [comment]
這樣好像就可以不用再寫圖例了

我再思考一下

**Comment by wastu01** [comment]
另外庫存大於等於 
理論上範圍應該大於0

**Comment by becory** [comment]
你是說有目前有可以負值的情況嗎？

**Comment by becory** [comment]
我自己感覺如果加太多常用藥局在列表上，感覺深色閱讀起來不太舒服......
<img width="570" alt="image" src="https://user-images.githubusercontent.com/13202145/167292986-91a7afc3-3764-4990-8087-d4c1a0fb8fb7.png">

**Comment by wastu01** [comment]
對 這樣看紅色好鮮豔 😂

自行選擇那邊應該限定只能選擇 0 以上

謝謝製作網站
